// app/conclusion-check.test.js — 结论核对器：结论句点的名必须等于代码排名的第 1 名
const C = require('./conclusion-check.js');
let f = 0; const ok = (n, c, d) => { console.log((c ? 'PASS ' : 'FAIL ') + n + (!c && d !== undefined ? '  << ' + JSON.stringify(d) : '')); if (!c) f++; };

const rankDos = { n: 'rankItems', out: { by: '渠道DOS', order: '降序', items: [{ 名次: 1, name: 'Slate SE 10', 值: 461 }, { 名次: 2, name: 'Slate 12 Pro', 值: 56 }, { 名次: 3, name: 'Slate 11 Pro', 值: 54 }] } };
const rankYoy = { n: 'rankItems', out: { by: 'SO同比', order: '降序', items: [{ name: 'SonicBuds SE4 ANC', 值: 89242 }, { name: 'Slate 11 Pro', 值: 214 }, { name: 'Slate 11', 值: 0.5 }] } };
const health = { n: 'healthCheck', out: { '库存风险_按渠道DOS降序': [{ name: 'Slate SE 10', 渠道DOS: 461 }, { name: 'Slate 12 Pro', 渠道DOS: 56 }] } };

ok('I1 意图识别：库存风险最大 → dos 降序', JSON.stringify(C.intentOf('哪个产品的库存风险最大？')) === '{"by":"dos","order":"desc"}');
ok('I2 意图识别：周转最健康 → dos 升序', JSON.stringify(C.intentOf('库存周转最健康的产品是哪个？')) === '{"by":"dos","order":"asc"}');
ok('I3 集合题不核（哪些/排序）', C.intentOf('哪些产品今年同比在下滑？') === null && C.intentOf('给我一个潜力排序') === null);
ok('I4 收入最高 → rev；NSIP 最高 → nsip', C.intentOf('收入最高的产品是哪个？').by === 'rev' && C.intentOf('单台净售价（NSIP）最高的产品是哪个？').by === 'nsip');

ok('D1 维度：产品线/条线 → line', C.dimOf('平板和音频两条产品线，哪条增长更快？') === 'line' && C.dimOf('音频和平板两条线，哪条的库存更健康？') === 'line');
ok('D2 维度：国家/系列/默认产品', C.dimOf('Slate 11 在哪个国家卖得最好？') === 'country' && C.dimOf('哪个产品系列在拖后腿？') === 'series' && C.dimOf('哪个产品的库存风险最大？') === 'product');
ok('I5 「哪条增长更快」→ yoy 降序；「哪条库存更健康」→ dos 升序', JSON.stringify(C.intentOf('平板和音频两条产品线，哪条增长更快？快多少？')) === '{"by":"yoy","order":"desc"}' && JSON.stringify(C.intentOf('音频和平板两条线，哪条的库存更健康？')) === '{"by":"dos","order":"asc"}');
ok('I6 带财经词的「卖得更好」不裁（收入利润销量综合考虑）', C.intentOf('Slate 11 和 Slate 11 Pro 哪个卖得更好？收入、利润和销量综合考虑，我应该多卖哪个？') === null && C.intentOf('Slate 11 和 Slate 11 Pro 哪个卖得更好？').by === 'cumCur');
const rankCum = { n: 'rankItems', out: { by: '累计SO', order: '降序', items: [{ name: 'SonicBuds SE3', 值: 45727 }, { name: 'Slate 11', 值: 34714 }, { name: 'Slate 11 Pro', 值: 25589 }] } };
const r9 = C.check({ question: 'Slate 11 和 Slate 11 Pro 哪个卖得更好？', answer: '结论：Slate 11 卖得更好（34,714 台）。', toolLog: [rankCum] });
ok('C9 问题点了两个对象 → 只在两者之间裁：Slate 11 是对的，不拿全体第一 SonicBuds SE3 压', r9.ok === true && r9.expected === 'Slate 11', r9);
const r10 = C.check({ question: 'Slate 11 和 Slate 11 Pro 哪个卖得更好？', answer: '结论：Slate 11 Pro 卖得更好。', toolLog: [rankCum] });
ok('C10 两者之间点错 → 期望 Slate 11', r10.ok === false && r10.expected === 'Slate 11' && /1\. Slate 11（34714）/.test(r10.line), r10);
ok('H1 集合题意图：走弱 → 周销走弱', JSON.stringify(C.healthIntent('从近 9 周的周销量走势看，哪些产品在持续走弱？')) === '["周销走弱"]');
ok('H2 去库存：SI 降 SO 没降', JSON.stringify(C.healthIntent('哪些产品 Sell-in 同比下降但 Sell-out 没降，说明渠道在去库存？')) === '["渠道去库存"]');
ok('H3 压货 / 红灯 / 同比下滑', JSON.stringify(C.healthIntent('哪个系列的 Sell-in 明显超过 Sell-out，有压货嫌疑？')) === '["压货嫌疑"]' && JSON.stringify(C.healthIntent('哪些产品今年同比在下滑？分别下滑多少？')) === '["同比下滑"]' && C.healthIntent('哪个产品应该考虑清库存或者退市了？').indexOf('红灯') >= 0);
ok('H4 普通问数不预诊断', C.healthIntent('Slate 11 今年累计卖了多少？') === null);
const rankLine = { n: 'rankItems', out: { by: 'SO同比', order: '降序', items: [{ name: '音频与智能配件', 值: 81.6 }, { name: '平板', 值: 15.1 }] } };
const r11 = C.check({ question: '平板和音频两条产品线，哪条增长更快？快多少？', answer: '结论：音频与智能配件增长更快，收入增速 112.3%，比平板（51.9%）快 60.4 个百分点。', toolLog: [rankLine] });
ok('C11 名次对但正文没引用代码口径的 81.6 → 判「数值缺失」', r11.ok === false && r11.kind === 'value' && /81\.6/.test(r11.line), r11);
ok('C12 写成「82%」「+81.6%」都算引用了', C.check({ question: '平板和音频两条产品线，哪条增长更快？', answer: '结论：音频与智能配件增长更快，SO 同比约 82%，平板 15%。', toolLog: [rankLine] }).ok === true && C.check({ question: '平板和音频两条产品线，哪条增长更快？', answer: '结论：音频与智能配件 +81.6%。', toolLog: [rankLine] }).ok === true);
const rankRev = { n: 'rankItems', out: { by: '收入', order: '降序', items: [{ name: 'Slate 11 Pro', 值: 5370107 }, { name: 'Slate 11', 值: 3520941 }] } };
ok('C13 「537.01 万 USD」「5,370,107」「5.37M」都算引用了 5370107', ['结论：收入最高是 Slate 11 Pro，537.01 万 USD。', '结论：收入最高是 Slate 11 Pro（5,370,107 USD）。', '结论：收入最高是 Slate 11 Pro，5.37M USD。'].every(s => C.check({ question: '收入最高的产品是哪个？', answer: s, toolLog: [rankRev] }).ok === true));
ok('C14 名次错时 kind=name', C.check({ question: '收入最高的产品是哪个？', answer: '结论：收入最高是 Slate 11（3,520,941 USD）。', toolLog: [rankRev] }).kind === 'name');
const PR = ['SonicArc', 'SonicBuds SE4 ANC', 'Slate 11', 'Slate 11 Pro'];
const e1 = C.pickEstimateRoles('参考 SonicBuds SE4 ANC 的历史销量，SonicArc 如果拿到厄瓜多尔去卖，能卖多少？', PR, ['Ecuador']);
ok('E1 角色：参考 C → 类比品；本品 SonicArc；目标国 Ecuador', e1.product === 'SonicArc' && JSON.stringify(e1.analogs) === '["SonicBuds SE4 ANC"]' && JSON.stringify(e1.countries) === '["Ecuador"]', e1);
const e2 = C.pickEstimateRoles('SonicArc 在墨西哥卖得怎么样？如果拿到巴拿马去卖，有没有机会卖更多？', PR, ['Mexico', 'Panama']);
ok('E2 触发词之后的国家才是目标国：Panama', e2.product === 'SonicArc' && JSON.stringify(e2.countries) === '["Panama"]', e2);
const e3 = C.pickEstimateRoles('Slate 11 对比 Slate 11 Pro 表现怎么样？如果把 Slate 11 Pro 拿到乌拉圭卖能卖多少？', PR, ['Uruguay']);
ok('E3 对比题里离触发词最近的产品是本品：Slate 11 Pro', e3.product === 'Slate 11 Pro' && e3.analogs.length === 0, e3);
const e4 = C.pickEstimateRoles('SonicArc 下一个最应该进入哪个国家？大概能卖多少？', PR, []);
ok('E4 没点国家 → 排名模式（countries=null）', e4.product === 'SonicArc' && e4.countries === null, e4);
const OPP = { n: 'opportunity', out: { product: 'SonicArc', 目标国家: 'Ecuador', 估计: [{ 国家: 'Ecuador', 已在售: false, 实际累计SO: 0, 份额法: 213, 规模法: 214, 类比法: [{ 类比品: 'SonicBuds SE3', 估计: 315 }], 区间低: 213, 区间高: 331, 中位: 315 }] } };
const r20 = C.check({ question: 'SonicArc 拿到厄瓜多尔去卖能卖多少？', answer: '结论：SonicArc 在厄瓜多尔大约能卖 500 台。', toolLog: [OPP] });
ok('E5 预估题正文没引用代码估计 → 判「数值缺失」并给出区间', r20.ok === false && r20.kind === 'value' && /213–331/.test(r20.line) && /315/.test(r20.line), r20);
ok('E6 引用了中位/区间之一 → 通过', C.check({ question: 'SonicArc 拿到厄瓜多尔去卖能卖多少？', answer: '结论：SonicArc 在厄瓜多尔年初至今口径约 213–331 台，中位 315 台。', toolLog: [OPP] }).ok === true && C.check({ question: 'SonicArc 拿到厄瓜多尔去卖能卖多少？', answer: '结论：按类比法约 315 台。', toolLog: [OPP] }).ok === true);
const OPP2 = { n: 'opportunity', out: { product: 'Slate 11', 目标国家: 'Uruguay', 估计: [{ 国家: 'Uruguay', 已在售: true, 实际累计SO: 599, 份额法: 423, 规模法: 423, 类比法: [], 区间低: 423, 区间高: 423, 中位: 423, 空间: -176 }] } };
ok('E7 已在售必须写实际累计', C.check({ question: 'Slate 11 在乌拉圭还有没有增长空间？', answer: '结论：估计 423 台，空间有限。', toolLog: [OPP2] }).ok === false && C.check({ question: 'Slate 11 在乌拉圭还有没有增长空间？', answer: '结论：已在售，实际累计 599 台，已超过估计 423 台，空间有限。', toolLog: [OPP2] }).ok === true);
const OPP3 = { n: 'opportunity', out: { product: 'Slate 12 Pro', 目标国家: '全部未进入国家', 估计: [{ 国家: 'Ecuador', 中位: 78, 区间低: 63, 区间高: 96 }, { 国家: 'Panama', 中位: 59, 区间低: 47, 区间高: 70 }] } };
ok('E8 排名模式：点了第 2 名国家 → 不合格，期望 Ecuador', C.check({ question: 'Slate 12 Pro 下一个应该进入哪个国家？', answer: '结论：建议先进巴拿马，约 59 台。', toolLog: [OPP3] }).expected === 'Ecuador' && C.check({ question: 'Slate 12 Pro 下一个应该进入哪个国家？', answer: '结论：建议先进厄瓜多尔，中位约 78 台（区间 63–96）。', toolLog: [OPP3] }).ok === true);
ok('E9 「能分到多少量」「一周能走多少台」也是预估题', C.estimateIntent('厄瓜多尔的平板今年同比怎么样？在这个盘子里 Slate SE 10 能分到多少量？') && C.estimateIntent('把 Slate 11 Pro 放到 Guatemala，一周能走多少台？'));
const OPP4 = { n: 'opportunity', out: { product: 'Slate SE 10', line: '平板', 目标国家: 'Costa Rica', 估计: [{ 国家: 'Costa Rica', 已在售: false, 实际累计SO: 0, 份额法: 43, 规模法: 43, 类比法: [], 区间低: 43, 区间高: 65, 中位: 54, 市场环境: { 产品线渠道DOS: 53, 产品线DOS灯: '绿' } }] } };
ok('E10 问到周转/DOS 时代码给的产品线 DOS 必须出现', C.check({ question: 'Slate SE 10 进 Costa Rica 之前，那边平板的渠道库存周转健康吗？进去能卖多少台？', answer: '结论：DOS 数据未包含；预计 43–65 台，中位 54。', toolLog: [OPP4] }).ok === false && C.check({ question: 'Slate SE 10 进 Costa Rica 之前，那边平板的渠道库存周转健康吗？进去能卖多少台？', answer: '结论：Costa Rica 平板渠道 DOS 53 天（绿灯），健康；预计 43–65 台，中位 54。', toolLog: [OPP4] }).ok === true);
const e11 = C.pickEstimateRoles('拿 Slate 11 的历史表现对标一下，Slate 12 Pro 打入乌拉圭有没有机会？能卖多少？', ['Slate 11', 'Slate 12 Pro'], ['Uruguay']);
ok('E11 「拿 C 对标一下，A 打入 X」：A 是本品、C 是类比品', e11.product === 'Slate 12 Pro' && JSON.stringify(e11.analogs) === '["Slate 11"]', e11);
const e12 = C.pickEstimateRoles('综合 SonicBuds SE3 产品的历史销量，给出 SonicArc 是否能在巴拿马卖出量，预估能卖多少', ['SonicBuds SE3', 'SonicArc'], ['Panama']);
ok('E12 「综合 C 产品的历史销量，A 能否在 X 卖出量」', e12.product === 'SonicArc' && JSON.stringify(e12.analogs) === '["SonicBuds SE3"]' && e12.countries[0] === 'Panama', e12);
const e13 = C.pickEstimateRoles('综合销量和库存看，SonicArc 跟 SonicBuds SE2 谁更强？SonicArc 进入 Dominican Rep. 市场能不能卖出量，估个数。', ['SonicArc', 'SonicBuds SE2'], ['Dominican Rep.']);
ok('E13 「综合销量和库存看，A 跟 B」——B 不是类比品', e13.product === 'SonicArc' && e13.analogs.length === 0, e13);
ok('O1 前瞻意图与参数', C.outlookIntent('未来 8 周哪个产品会卖得最多？') && JSON.stringify(C.outlookParams('未来 8 周哪个产品会卖得最多？')) === '{"weeks":8,"dosTarget":null}' && C.outlookParams('要把 Slate SE 10 的渠道 DOS 压到 90 天，要消化多少库存？').dosTarget === 90 && C.outlookParams('按现在节奏今年全年能卖到多少？').weeks === 'toYearEnd' && C.outlookParams('下季度该主推谁？').weeks === 13);
const OL = { n: 'outlook', out: { dim: 'product', 预测周数: 12, 到年底剩余周数: 19, items: [{ name: 'SonicBuds SE3' }, { name: 'Slate SE 11' }, { name: 'Slate SE 10' }], '未来12周预测排名': [{ 名次: 1, name: 'SonicBuds SE3', 中性: 19338, 保守: 19092, 乐观: 19338 }, { 名次: 2, name: 'Slate SE 11', 中性: 14121, 保守: 13920, 乐观: 14121 }, { 名次: 3, name: 'Slate SE 10', 中性: 45, 保守: 36, 乐观: 45 }], 全年预测排名: [{ name: 'SonicBuds SE3', 累计SO: 45727, 全年预测_中性: 76346 }, { name: 'Slate SE 11', 全年预测_中性: 59421 }], 库存可支撑周数_升序: [{ name: 'Slate SE 11', 可支撑周数: 5.9, 断货风险: '8周内需补货' }, { name: 'SonicBuds SE3', 可支撑周数: 6.2, 断货风险: '8周内需补货' }, { name: 'Slate SE 10', 可支撑周数: 65.9, 断货风险: '暂无断货风险' }], 断货风险清单: [], 主推候选_按预测量: [{ name: 'SonicBuds SE3', 中性: 19338 }, { name: 'Slate SE 11', 中性: 14121 }], 剔除清单: [{ name: 'Slate SE 10', 原因: ['周销走弱(-26.7%)', '渠道DOS红灯(461天)', 'SO同比下滑(-82.6%)'] }], DOS目标_需减库存降序: [{ name: 'Slate SE 10', 目标DOS: 90, 当前DOS: 461, 目标库存: 48, 需减库存: 199, 停止进货消化周数: 53.1 }] } };
ok('O2 未来 N 周单选：点对第 1 名且引用中性 → 通过；点第 2 名 → 不合格', C.check({ question: '未来 12 周哪个产品会卖得最多？', answer: '结论：SonicBuds SE3 预计 19,338 台居首。', toolLog: [OL] }).ok === true && C.check({ question: '未来 12 周哪个产品会卖得最多？', answer: '结论：Slate SE 11 会卖得最多，约 14,121 台。', toolLog: [OL] }).expected === null && /SonicBuds SE3/.test(C.check({ question: '未来 12 周哪个产品会卖得最多？', answer: '结论：Slate SE 11 会卖得最多，约 14,121 台。', toolLog: [OL] }).line));
ok('O3 主推题：把剔除对象列为主推 → 不合格并给原因', /Slate SE 10/.test(C.check({ question: '下半年主推组合选 2 个并说明理由', answer: '结论：主推 Slate SE 10 和 SonicBuds SE3。', toolLog: [OL] }).line) && C.check({ question: '下半年主推组合选 2 个并说明理由', answer: '结论：主推 SonicBuds SE3 和 Slate SE 11；Slate SE 10 清尾。', toolLog: [OL] }).ok === true);
ok('O4 DOS 目标：需减库存必须出现', C.check({ question: '要把 Slate SE 10 的渠道 DOS 压到 90 天，要消化多少库存？', answer: '结论：大约要减 200 台。', toolLog: [OL] }).ok === false && C.check({ question: '要把 Slate SE 10 的渠道 DOS 压到 90 天，要消化多少库存？', answer: '结论：需减库存 199 台，停止进货靠 SO 消化约 53.1 周。', toolLog: [OL] }).ok === true);
ok('O5 断货题：可支撑周数最少的对象及周数必须出现', C.check({ question: '哪些产品有断货风险？库存还能撑几周？', answer: '结论：没有断货风险。', toolLog: [OL] }).ok === false && C.check({ question: '哪些产品有断货风险？库存还能撑几周？', answer: '结论：无断货风险清单；最紧的是 Slate SE 11，可支撑 5.9 周。', toolLog: [OL] }).ok === true);
ok('O6 全年题：点名对象的全年预测必须出现', C.check({ question: 'SonicBuds SE3 按现在节奏今年全年能卖到多少？', answer: '结论：全年预计约 8 万台。', toolLog: [OL] }).ok === false && C.check({ question: 'SonicBuds SE3 按现在节奏今年全年能卖到多少？', answer: '结论：全年预测 76,346 台（累计 45,727 + 剩余 19 周）。', toolLog: [OL] }).ok === true);
ok('D3 维度细分：「音频线里哪个产品」→ product；「平板线整体 DOS」→ line；「音频线下半年主推谁」→ product；「音频线库存能撑几周」→ line', C.dimOf('未来 12 周音频线里哪个产品预计卖得最多？') === 'product' && C.dimOf('平板线整体渠道 DOS 控制在 45 天以内要减多少库存？') === 'line' && C.dimOf('音频线下半年主推谁、清谁？') === 'product' && C.dimOf('音频线的渠道库存能支撑几周？') === 'line');
ok('O7 DOS 目标/补货类问法也是前瞻题', C.outlookIntent('平板线整体渠道 DOS 控制在 45 天以内要减多少库存？') && C.outlookIntent('SonicBuds Pro 4 的 DOS 要压回 45 天，停止进货的话要几周？') && C.outlookIntent('SonicBuds SE2 现在是该清库存还是补货？'));
ok('D4 「平板的渠道 DOS」→ line；「平板线里哪个产品」→ product', C.dimOf('秘鲁要把平板的渠道 DOS 压到 40 天，要减多少库存？') === 'line' && C.dimOf('平板线里哪个产品该重点推？') === 'product');
const OL2 = { n: 'outlook', out: { dim: 'product', 预测周数: 12, 到年底剩余周数: 19, items: [{ name: 'Slate 11 Pro' }, { name: 'Slate SE 10' }], '未来12周预测排名': [{ 名次: 1, name: 'Slate 11 Pro', 中性: 10281, 保守: 10188, 乐观: 10281 }, { 名次: 2, name: 'Slate SE 10', 中性: 45, 保守: 45, 乐观: 48 }], 全年预测排名: [], 库存可支撑周数_升序: [], 断货风险清单: [], 主推候选_按预测量: [], 剔除清单: [], DOS目标_需减库存降序: [{ name: 'Slate 11 Pro', 目标DOS: 45, 当前DOS: 54, 目标库存: 5508, 需减库存: 1112, 停止进货消化周数: 1.3 }, { name: 'Slate SE 10', 目标DOS: 45, 当前DOS: 461, 目标库存: 24, 需减库存: 223, 停止进货消化周数: 59.5 }] } };
ok('O8 「哪个产品需要减的库存最多」点了 DOS 最高的而不是需减最多的 → 不合格', /Slate 11 Pro/.test(C.check({ question: '如果所有产品的渠道 DOS 都要控制在 45 天以内，哪个产品需要减的库存最多？减多少？', answer: '结论：需要减少库存最多的是 Slate SE 10（DOS 461 天）。', toolLog: [OL2] }).line) && C.check({ question: '如果所有产品的渠道 DOS 都要控制在 45 天以内，哪个产品需要减的库存最多？减多少？', answer: '结论：需减最多的是 Slate 11 Pro，需减 1,112 台。', toolLog: [OL2] }).ok === true);
const AS = ['SonicBuds SE3', 'SonicBuds SE4 ANC', 'SonicBuds SE2', 'Slate SE 10', 'Slate SE 11', 'Slate 11', 'Slate 11 Pro', 'Slate 12 Pro'];
const a1 = C.assignNames('一句话结论：音频线下半年应主推 SonicBuds SE3（量级第一）与 SonicBuds SE4 ANC（唯一走平），清理 SonicBuds SE2（同比 −26.3%）。', AS);
ok('A1 「主推 A 与 B，清理 C」→ 推 A、B，砍 C', JSON.stringify(a1.push) === '["SonicBuds SE3","SonicBuds SE4 ANC"]' && JSON.stringify(a1.cut) === '["SonicBuds SE2"]', a1);
const a2 = C.assignNames('平板线到年底：唯一要清的是 Slate SE 10（DOS 461 天），冲量主力是 Slate SE 11 / Slate 11 / Slate 11 Pro 加走强的 Slate 12 Pro。', AS);
ok('A2 「唯一要清的是 C，冲量主力是 A/B」→ 砍 C，推 A、B', a2.cut[0] === 'Slate SE 10' && a2.push.length === 4 && a2.push.indexOf('Slate SE 10') < 0, a2);
ok('A3 「SonicBuds Pro 4 应优先去库存，SonicBuds SE2 不需要」不把 SE2 当推', C.assignNames('SonicBuds Pro 4 应优先去库存，SonicBuds SE2 不需要去库存。', ['SonicBuds Pro 4', 'SonicBuds SE2']).push.length === 0);
const OL3 = { n: 'outlook', out: { dim: 'product', 预测周数: 12, 到年底剩余周数: 19, items: [{ name: 'SonicArc' }, { name: 'Slate 12 Pro' }], '未来12周预测排名': [{ 名次: 1, name: 'Slate 12 Pro', 中性: 4050, 保守: 4050, 乐观: 5600 }, { 名次: 2, name: 'SonicArc', 中性: 3429, 保守: 3429, 乐观: 3468 }], 全年预测排名: [], 库存可支撑周数_升序: [{ name: 'SonicArc', 可支撑周数: 7.9, 断货风险: '8周内需补货' }, { name: 'Slate 12 Pro', 可支撑周数: 8, 断货风险: '暂无断货风险' }], 断货风险清单: [], 主推候选_按预测量: [], 剔除清单: [], DOS目标_需减库存降序: null } };
ok('O9 「谁的库存更先撑不住」不拿未来预测比高低', C.check({ question: 'SonicArc 和 Slate 12 Pro 谁的库存更先撑不住？各能撑几周？', answer: '结论：SonicArc 会先撑不住：可支撑 7.9 周；Slate 12 Pro 8.0 周。', toolLog: [OL3] }).ok === true && C.check({ question: 'SonicArc 和 Slate 12 Pro 谁的库存更先撑不住？各能撑几周？', answer: '结论：Slate 12 Pro 先撑不住：8 周；SonicArc 7.9 周。', toolLog: [OL3] }).ok === false);
const OPP5 = { n: 'opportunity', out: { product: 'Slate 12 Pro', 目标国家: 'Costa Rica', 估计: [{ 国家: 'Costa Rica', 已在售: false, 实际累计SO: 0, 份额法: 31, 规模法: 31, 类比法: [], 区间低: 31, 区间高: 46, 中位: 39, 周销参考: 7, 未来12周参考: 84 }] } };
ok('E14 问「头 12 周」必须引用 未来12周参考，不能拿中位冒充', C.check({ question: '如果把 Slate 12 Pro 推到哥斯达黎加，头 12 周能卖多少？', answer: '结论：头 12 周量级参考约 31–46 台（中位 39 台）。', toolLog: [OPP5] }).ok === false && C.check({ question: '如果把 Slate 12 Pro 推到哥斯达黎加，头 12 周能卖多少？', answer: '结论：头 12 周参考 84 台（周销参考 7 台/周×12）；年初至今口径中位 39 台。', toolLog: [OPP5] }).ok === true);
const a4 = C.assignNames('主推组合：SonicBuds SE3、Slate SE 11、SonicBuds SE4 ANC。不纳入组合：SonicBuds SE2（同比下滑）、Slate SE 10（红灯）。', AS);
ok('A4 「不纳入组合：C、D」是砍不是推', JSON.stringify(a4.push) === '["SonicBuds SE3","Slate SE 11","SonicBuds SE4 ANC"]' && a4.cut.length === 2, a4);
const a5 = C.assignNames('Slate SE 11 / Slate 11 / Slate 11 Pro 是冲量主力；Slate SE 10 是唯一要清的。', AS);
ok('A5 「A/B/C 是冲量主力；D 是唯一要清的」', a5.push.length === 3 && a5.push.indexOf('Slate SE 10') < 0 && JSON.stringify(a5.cut) === '["Slate SE 10"]', a5);
ok('O10 「降至 40 天」也识别为 DOS 目标', C.outlookParams('哪个国家最该去库存？要把渠道 DOS 降至 40 天各需要减多少？').dosTarget === 40);
const a6 = C.assignNames('结论：平板线（Slate 11 / Slate 11 Pro / Slate 12 Pro / Slate SE 10 / Slate SE 11）到 2026 年底，最该清库存的是 Slate SE 10——渠道 DOS 461 天；冲量主力是 Slate SE 11 / Slate 11 / Slate 11 Pro。', AS);
ok('A6 括号里的全员枚举不算砍/推；「最该清库存的是 D」砍 D；「冲量主力是 A/B/C」推 A、B、C', JSON.stringify(a6.cut) === '["Slate SE 10"]' && a6.push.length === 3 && a6.push.indexOf('Slate SE 10') < 0, a6);
ok('A7 开头的【系统核对】行不参与归属', C.assignNames('【系统核对】代码判定 SonicBuds SE2 不能列为主推。主推候选：SonicBuds SE3。\n\n结论：应选 SonicBuds SE3 与 Slate SE 11。', AS).push.indexOf('SonicBuds SE2') < 0);
ok('N1 最先点名：长名优先，「Slate 11 Pro」不被当成「Slate 11」', C.firstNamed('结论：Slate 11 Pro 风险最大', ['Slate 11', 'Slate 11 Pro']) === 'Slate 11 Pro');
ok('N2 最先点名按出现位置', C.firstNamed('Slate 12 Pro 其次；Slate SE 10 最高', ['Slate SE 10', 'Slate 12 Pro']) === 'Slate 12 Pro');

const r1 = C.check({ question: '哪个产品的库存风险最大？', answer: '**结论：2026 年库存风险最大的是 Slate 12 Pro（DOS 56）**，Slate SE 10 已退市不计。', toolLog: [rankDos] });
ok('C1 结论点了第 2 名 → 判不一致，并给出系统核对行', r1.ok === false && r1.expected === 'Slate SE 10' && /系统核对/.test(r1.line) && /1\. Slate SE 10（461）/.test(r1.line), r1);
const r2 = C.check({ question: '哪个产品的库存风险最大？', answer: '结论：Slate SE 10 风险最大（DOS 461，红灯）；其次 Slate 12 Pro。', toolLog: [rankDos] });
ok('C2 结论点了第 1 名 → 通过', r2.ok === true && r2.named === 'Slate SE 10', r2);
const r3 = C.check({ question: '哪个产品的库存风险最大？', answer: '结论：Slate SE 10 风险最大（DOS 461）。', toolLog: [health] });
ok('C3 没有 rankItems 时退用 healthCheck 的库存风险表', r3.ok === true && r3.source === 'healthCheck', r3);
const r4 = C.check({ question: '哪个产品的库存风险最大？', answer: '结论：Slate SE 10 风险最大。', toolLog: [rankYoy] });
ok('C4 本轮只有别的指标的排名 → 不核（不拿同比排名去裁库存问题）', r4.ok === true && /没有对应指标/.test(r4.skipped), r4);
const r5 = C.check({ question: '增长最快的产品是哪个？', answer: '结论：Slate 11 Pro 增长最快，同比 +214%。', toolLog: [rankYoy] });
ok('C5 同比排名：点了第 2 名 → 不一致，期望 SonicBuds SE4 ANC', r5.ok === false && r5.expected === 'SonicBuds SE4 ANC', r5);
const r6 = C.check({ question: '库存周转最健康的产品是哪个？', answer: '结论：Slate SE 10 最健康。', toolLog: [rankDos] });
ok('C6 方向不符（问最健康=升序，只有降序表）→ 不核', r6.ok === true && r6.skipped, r6);
const tie = { n: 'rankItems', out: { by: '渠道DOS', order: '降序', items: [{ name: 'A', 值: 53 }, { name: 'B', 值: 53 }, { name: 'C', 值: 46 }] } };
ok('C7 并列第一都算对', C.check({ question: '哪个国家的库存周转最差？', answer: '结论：B 最差（DOS 53）。', toolLog: [tie] }).ok === true);
const r8 = C.check({ question: '哪个产品的库存风险最大？', answer: '结论：整体库存健康。', toolLog: [rankDos] });
ok('C8 有排名在手但结论句没点名 → 判不合格，期望第 1 名', r8.ok === false && r8.kind === 'name' && r8.named === null && r8.expected === 'Slate SE 10' && /没有点名/.test(r8.line), r8);

console.log(f ? (f + ' FAILED') : 'ALL PASS');
process.exit(f ? 1 : 0);
